cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('authorization/', include('authorization.urls')),
    path('church/', include('church.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path, include
from . import views

app_name='payment'

urlpatterns = [
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('checkout/', views.checkout, name='checkout'),
    path('billing_info/', views.billing_info, name='billing_info'),
    path('process_payment/', views.process_payment, name='process_payment'),
    path('shipped_dash/', views.shipped_dash, name='shipped_dash'),
    path('not_shipped_dash/', views.not_shipped_dash, name='not_shipped_dash'),
    path('orders/<int:pk>/', views.orders, name='orders'),
    path('update_shipping_status/', views.update_shipping_status, name='update_shipping_status'),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

store/urls.py
from django.urls import path
from . import views

app_name='store'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('update_password/', views.update_password, name='update_password'),
    path('product/<int:pk>/', views.product, name='product'),
    path('category/<str:foo>/', views.category, name='category'),
    path('categoty_summary/', views.category_summary, name='category_summary'),
    path('search/', views.search, name='search'),
]

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib import messages
from store.models import Product
from .cart import Cart
from authorization.authorize import Authorization

# Create your views here.
def cart_summary(request):
    #get the cart
    cart = Cart(request)
    #get products
    cart_products = cart.get_prods()
    #get quantities
    quantities = cart.get_quants();
    #get totals
    totals = cart.get_total()
    #preparing data
    context = {
        'cart_products' : cart_products,
        'quantities' : quantities,
        'totals': totals,
    }
    return render(request, 'cart/cart_summary.html', context)

def cart_add(request):
    #get the cart
    cart = Cart(request)
    #testing
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        #Quantity
        product_qty = int(request.POST.get('product_qty'))
        #fetch product
        product = get_object_or_404(Product, id=product_id)
        #save to session
        cart.add(product=product, quantity=product_qty)
        #Now Calculate cart length 
        cart_quantity = len(cart)
        #messages.success(request, ('[ cart > add ] : You have successful added ' + product.name + ' with quantity ' + product_qty))
        messages.success(request, ('Successful Added the product'))
        #build response
        response = JsonResponse({ 'qty' : cart_quantity })
        return response
    else:
        messages.success(request, ('There were problem in adding a product'))
        return JsonResponse({'error' : '707', 'errormessage' : 'Could not get a valid action'})

def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        cart = Cart(request)
        product_id = int(request.POST.get('product_id'))
        #Delete cart
        cart.delete(product=product_id)
        #messages
        messages.success(request, ('An item was deleted, successful'))
        #build response
        response = JsonResponse({ 'product' : product_id })
        return response
    else:
        #messages
        messages.success(request, ('Failed to remove an item'))
        #response
        return JsonResponse({'error' : '808', 'errormessage' : 'Could not get a valid action'})

def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        #update cart
        cart.update(product=product_id, quantity=product_qty)
        #messages
        messages.success(request, ('An item was updated, successful'))
        #build response
        response = JsonResponse({ 'qty' : product_qty })
        return response
    else:
        #messages
        messages.success(request, ('Failed to update an item'))
        #response
        return JsonResponse({'error' : '707', 'errormessage' : 'Could not get a valid action'})

templates/cart/cart_summary.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shopping Cart</h1>
            <p class="lead fw-normal text-white-50 mb-0">View Your Cart</p>
        </div>
    </div>
</header>
<!-- Section-->
<div class="container">
    {% if cart_products %}
    {% for product in cart_products %}
    <!--Begin : Card-->
    <div class="card mb-2 mt-2">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{%if product.image %}{{ product.image.url }}{% endif %}" class="img-fluid rounded-start"
                    alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <center>
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <br />
                        {% if product.is_sale %}
                        <!--Sales Information-->
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star-fill"></div>
                            &nbsp;&nbsp;Sale!&nbsp;&nbsp;
                            <div class="bi-star-fill"></div>
                        </div>
                        <!-- Product price-->
                        <strike>${{ product.price }}</strike> &nbsp;&nbsp;${{ product.sale_price }}&nbsp;&nbsp;
                        {% else %}
                        <!-- Product price-->
                        ${{ product.price }}
                        {% endif %}
                        <br /><br />
                        <div class="row justify-content-center">
                            <div class="col-md-2">Quantity</div>
                            <div class="col-md-2">
                                <select id="select{{ product.id }}" class="form-select form-select-sm" aria-label="Product Quantity">
                                    {% for key, value in quantities.items %}
                                        {% if key == product.id|slugify %}
                                            <option value="{{ value }}">{{ value }}</option>
                                        {% endif %}
                                    {% endfor %}
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                </select>
                            </div>
                        </div>
                        <br />
                        <p><small>In : {{ product.category }}</small></p>
                        <br/>
                        <small><i><a href="{% url 'store:home' %}" class="btn btn-secondary">Go to Home</a></i></small>
                        &nbsp;&nbsp;
                        <small><i><button type="button" data-index="{{ product.id }}" class="btn btn-secondary update-cart">Update</button></i></small>
                        &nbsp;&nbsp;
                        <small><i><button type="button" data-index="{{ product.id }}" class="btn btn-danger delete-product">Remove</button></i></small>
                        <br />
                    </center>
                </div>
            </div>
        </div>
    </div>
    <!--End : Card-->
    {% endfor %}
    <!--Handling Total-->
    <div align="right">
        <h3>Total : ${{ totals }}</h3>
        <a href="{% url 'payment:checkout' %}" class="btn btn-success">Checkout</a>
    </div>
    <br/><br/><br/>
    {% else %}
    <br /><br /><br /><br />
    <div class="alert alert-warning" role="alert">
        You have nothing in your cart!!!!
    </div>
    <br /><br /><br /><br />
    {% endif %}
</div>
{% endblock %}
{% block script %}
<script>
    (function ($) {
        $(function () {
            /* Update Cart */
            $(document).on('click', '.update-cart', function (e) {
                e.preventDefault();
                var productid = $(this).data('index');
                $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_update" %}',
                    data: {
                        product_id: productid,
                        product_qty: $('#select' + productid + ' option:selected').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        action: 'post'
                    },
                    success: function (json) {
                        window.location.reload();
                    },
                    error: function (xhr, errmsg, err) { 
                        window.location.reload();
                    }
                });
            });
            /* Remove Product */
            $(document).on('click', '.delete-product', function (e) {
                e.preventDefault();
                var productid = $(this).data('index');
                $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_delete" %}',
                    data: {
                        product_id: productid,
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        action: 'post'
                    },
                    success: function (json) {
                        window.location.reload();
                    },
                    error: function (xhr, errmsg, err) { 
                        window.location.reload();
                    }
                });
            });
        });
    })(jQuery);
</script>
{% endblock %}