cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

church/urls.py
from django.urls import path
from . import views

app_name='church'

urlpatterns = [
    path('', views.load_by_name, name='load_by_name'),
    path('load_by_position', views.load_by_position, name='load_by_position'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('authorization/', include('authorization.urls')),
    path('church/', include('church.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

church/models.py
from django.db import models

# Create your models here.

church/views.py
from django.shortcuts import render, redirect
from django.conf import settings
import os
import pandas as pd

church_name="Gorfan SDA Church"
# Create your views here.
def load_by_name(request):
    file_path = os.path.join(settings.BASE_DIR, '__my_church_data__', 'viongozi_2026.csv')
    context = {"church_name" : church_name}
    try:
        data = pd.read_csv(file_path, sep='|')
        if "Jina" not in data.columns:
            raise Exception("Jina not found in a column")
        list_of_names = data['Jina'].unique().tolist()
        list_of_names.sort(key=str)
        context['list_of_names'] = list_of_names
        #Now if this is POST we need to append , list of position
        if request.method == "POST":
            selected_name = request.POST['selected_name']
            if "Nafasi" not in data.columns:
                raise Exception("Nafasi not found in a column")
            selected_records = data[data['Jina']==selected_name]
            list_of_positions = selected_records['Nafasi'].tolist();
            list_of_positions.sort(key=str)
            context['selected_name'] = selected_name
            context['list_of_positions'] = list_of_positions
    except FileNotFoundError:
        context['data'] = "File Not Found"
    except Exception as e:
        context['data'] = "General Error"
    return render(request, "church/load_by_name.html", context)

def load_by_position(request):
    return render(request, "church/load_by_position.html", {})

templates/church/load_by_name.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{ church_name }}</h1>
            <p class="lead fw-normal text-white-50 mb-0">My Church...</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <!--I have a list in products variable -->
    {% if list_of_names %}
        <section class="body">
            <form method="POST" action="{% url 'church:load_by_name' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="selected_name" class="form-label">Name (Jina 
                        {% if selected_name %}
                            = "{{ selected_name }}"
                        {% endif %}
                    ) : 
                    </label>
                    <select name="selected_name" id="selected_name" class="form-select" aria-label="Default select example">
                        <option value="-1" selected>Open this select menu</option>
                        {% for name in list_of_names %}
                            <option value="{{name}}">{{name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </section>
        <!--Position for this name-->
        {% if list_of_positions %}
        <section class="body my-3 px-25">
            <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Position</th>
                  </tr>
                </thead>
                <tbody>
                {% for position in list_of_positions %}
                <tr>
                    <td>{{ position }}</td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
        </section>
        {% endif %}
    {% else %}
        <section class="body">
            <h1>We did not find names</h1>
        </section>
    {% endif %}
</section>
{% endblock %}

templates/church/load_by_position.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Load by Position</title>
</head>
<body>
    <h1>Load by Position</h1>
</body>
</html>