cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('authorization/', include('authorization.urls')),
    path('church/', include('church.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path, include
from . import views

app_name='payment'

urlpatterns = [
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('checkout/', views.checkout, name='checkout'),
    path('billing_info/', views.billing_info, name='billing_info'),
    path('process_payment/', views.process_payment, name='process_payment'),
    path('shipped_dash/', views.shipped_dash, name='shipped_dash'),
    path('not_shipped_dash/', views.not_shipped_dash, name='not_shipped_dash'),
    path('orders/<int:pk>/', views.orders, name='orders'),
    path('update_shipping_status/', views.update_shipping_status, name='update_shipping_status'),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

store/urls.py
from django.urls import path
from . import views

app_name='store'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('update_password/', views.update_password, name='update_password'),
    path('product/<int:pk>/', views.product, name='product'),
    path('category/<str:foo>/', views.category, name='category'),
    path('categoty_summary/', views.category_summary, name='category_summary'),
    path('search/', views.search, name='search'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Django -- ECommerce</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'bs/assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="{% static 'bs/css/bootstrap-4.3.1.min.css' %}" rel="stylesheet"/>-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'bs/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    {% include 'navbar.html' %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <i>{{ message }}</i>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
    <!--jQuery cdn-->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <!-- <script src="{% static 'jquery/js/jquery-3.6.0.min.js' %}"></script>-->
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!--<script src="{% static 'bs/js/bootstrap-4.3.1.min.js' %}"></script>-->
    <!-- Core theme JS-->
    <script src="{% static 'bs/js/scripts.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>

</html>

templates/category.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{ category }}</h1>
            <p class="lead fw-normal text-white-50 mb-0">Products in Category...</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <!--I have a list in products variable -->
    {% include 'product_list.html' %}
</section>
{% endblock %}

templates/category_summary.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Category ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Choose from Categories ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 text-center">
        <p align="justify">
            {% for category in categories %}
                <h3><a href="{% url 'store:category' category %}">{{ category }}</a></h3>
            {% endfor %}
        </p>
    </div>
</section>
    {% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <!--I have a list in products variable -->
    {% include 'product_list.html' %}
</section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Login ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Login to your account ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 col-md-6">
        <!--Begin: Login Form-->
        <form method="POST" action="{% url 'store:login' %}">
            {% csrf_token %}
            <div class="mb-3">
              <input type="text" class="form-control" name="username">
            </div>
            <div class="mb-3">
              <input type="password" class="form-control" name="password">
            </div>
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Log In</button>
        </form>
        <!--End: Login Form-->
    </div>
</section>
    {% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'store:home' %}">
            {% if user.is_authenticated %}
                Welcome {{ user.username }}
            {% else %}
                Welcome to Ecommerce
            {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page"
                        href="{% url 'store:home' %}">Home</a></li>
                <li class="nav-item"><a href="{% url 'store:search' %}" class="nav-link">Search</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'store:about' %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown2" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'store:update_user' %}">User Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'store:update_info' %}">User Info</a></li>
                    </ul>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown2" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">Orders</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'payment:shipped_dash' %}">Shipped Orders</a></li>
                        <li><a class="dropdown-item" href="{% url 'payment:not_shipped_dash' %}">Unshipped Orders</a></li>
                    </ul>
                </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'store:logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}">Log In</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'store:register' %}">Register</a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'store:category_summary' %}">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li><a class="dropdown-item" href="{% url 'store:category' 'Programming-Books' %}">Programming
                                Books</a></li>
                        <li><a class="dropdown-item" href="{% url 'store:category' 'Phone' %}">Cellular Phones</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <a class="btn btn-outline-dark" href="{% url 'cart:cart_summary' %}">
                    <i class="bi-cart-fill me-1"></i>
                    Cart
                    <span id="cart_quantity" class="badge bg-dark text-white ms-1 rounded-pill">{{cart|length}}</span>
                </a>
            </form>
        </div>
    </div>
</nav>

templates/not_allowed.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Not Allowed ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Rules Violated ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="bg-danger text-white">
            NOT ALLOWED
        </div>
    </div>
</section>
    {% endblock %}

templates/product.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <br /><br />
    <!--Begin : Card-->
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{%if product.image %}{{ product.image.url }}{% endif %}" class="img-fluid rounded-start"
                    alt="...">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <center>
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <br />
                        {% if product.is_sale %}
                        <!--Sales Information-->
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            <div class="bi-star-fill"></div>
                            &nbsp;&nbsp;Sale!&nbsp;&nbsp;
                            <div class="bi-star-fill"></div>
                        </div>
                        <!-- Product price-->
                        <strike>${{ product.price }}</strike> &nbsp;&nbsp;${{ product.sale_price }}&nbsp;&nbsp;
                        {% else %}
                        <!-- Product price-->
                        ${{ product.price }}
                        {% endif %}
                        <br /><br />
                        <div class="row justify-content-center">
                            <div class="col-md-2">Quantity</div>
                            <div class="col-md-2">
                                <select id="qty-cart" class="form-select form-select-sm" aria-label="Product Quantity">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                </select>
                            </div>
                        </div>
                        <br />
                        <p><small>In : {{ product.category }}</small></p>
                        <br />
                        <small><i><a href="{% url 'store:home' %}" class="btn btn-secondary">Go to Home</a></i></small>
                        &nbsp;&nbsp;
                        <small><i><button class="btn btn-secondary" type="button" value="{{product.id}}"
                                    id="add-cart">Add To Cart</button></i></small>
                        <br />
                    </center>
                </div>
            </div>
        </div>
    </div>
    <!--End : Card-->
    <br /><br />
</div>
{% endblock %}
{% block script %}
<script>
    (function ($) {
        $(function () {
            $(document).on('click', '#add-cart', function (e) {
                e.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_add" %}',
                    data: {
                        product_id: $(this).val(),
                        product_qty: $('#qty-cart option:selected').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        action: 'post'
                    },
                    success: function (json) {
                        document.getElementById('cart_quantity').textContent = json.qty;
                        window.location.href = '{% url "store:home" %}';
                    },
                    error: function (xhr, errmsg, err) {
                        window.location.href = '{% url "store:home" %}';
                     }
                });
            });
        });
    })(jQuery);
</script>
{% endblock %}

templates/product_list.html
<!--Must have a variable products ; which is a list of product -->
{% if products %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for product in products %}
        {% if product.is_sale %}
        <div class="col mb-5">
            <a href="{% url 'store:product' product.id %}" class="text-decoration-none">
                <div class="card h-100">
                    <!--Sale Badge-->
                    <div style="top:0.5rem; right: 0.5rem;" class="badge bg-dark text-white position-absolute">Sale
                    </div>
                    <!-- Product image-->
                    <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{%endif %}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!--Sales Information-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                &nbsp;&nbsp;Sale!&nbsp;&nbsp;
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            <strike>${{ product.price }}</strike> &nbsp;&nbsp;${{ product.sale_price }}&nbsp;&nbsp;
                            <br />
                            in : {{ product.category }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                href="{% url 'store:product' product.id %}">View Product</a></div>
                    </div>
                </div>
            </a>
        </div>
        {% else %}
        <div class="col mb-5">
            <a href="{% url 'store:product' product.id %}" class="text-decoration-none">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{%endif %}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            ${{ product.price }}
                            <br />
                            in : {{ product.category }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                href="{% url 'store:product' product.id %}">View Product</a></div>
                    </div>
                </div>
            </a>
        </div>
        {% endif %}

        {% endfor %}
    </div>
</div>
{% endif %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Register ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Registering a New User ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 col-md-6">
        <!--Begin: Login Form-->
        <form method="POST" action="{% url 'store:register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Register</button>
        </form>
        <!--End: Login Form-->
    </div>
</section>
    {% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Seach Products ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Find What You are Looking for ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="card">
            <div class="card-header">
                Search Products
            </div>
            <div class="card-body">
                <form method="POST" action="{% url 'store:search' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input type="text" class="form-control" name="searched" placeholder="Item to Search">
                    </div>
                    <div class="mb-3 d-flex justify-content-end">
                        <button type="submit" class="btn btn-secondary">Search Products</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<section class="py-5">
    <!--No need of testing product as the include test by itself-->
    {% include 'product_list.html' %}
</section>
{% endblock %}

templates/update_info.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Update Info ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Updating User Info ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 col-md-6">
        <!--Begin: Login Form-->
        <form method="POST" action="{% url 'store:update_info' %}">
            {% csrf_token %}
            <strong>Billing Information</strong>
            {{ form.as_p }}
            <br/><br/>
            <strong>Shipping Information</strong>
            {{ shipping_form.as_p }}
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Update Profile</button>
        </form>
        <!--End: Login Form-->
    </div>
</section>
    {% endblock %}

templates/update_password.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Update Password ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Updating Password ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 col-md-6">
        <!--Begin: Login Form-->
        <form method="POST" action="{% url 'store:update_password' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Update Password</button>
        </form>
        <!--End: Login Form-->
    </div>
</section>
    {% endblock %}

templates/update_user.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Update Profile ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Updating User Profile ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5 col-md-6">
        <!--Begin: Login Form-->
        <form method="POST" action="{% url 'store:update_user' %}">
            {% csrf_token %}
            {{ user_form.as_p }}
            <br/><br/>
            <button type="submit" class="btn btn-secondary">Update Profile</button>
        </form>
        <!--End: Login Form-->
    </div>
</section>
    {% endblock %}