cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),
    path('authorization/', include('authorization.urls')),
    path('church/', include('church.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path, include
from . import views

app_name='payment'

urlpatterns = [
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_failed/', views.payment_failed, name='payment_failed'),
    path('checkout/', views.checkout, name='checkout'),
    path('billing_info/', views.billing_info, name='billing_info'),
    path('process_payment/', views.process_payment, name='process_payment'),
    path('shipped_dash/', views.shipped_dash, name='shipped_dash'),
    path('not_shipped_dash/', views.not_shipped_dash, name='not_shipped_dash'),
    path('orders/<int:pk>/', views.orders, name='orders'),
    path('update_shipping_status/', views.update_shipping_status, name='update_shipping_status'),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

payment/models.py
from django.db import models
from authorization.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
import datetime
from store.models import Product

# Create your models here.
class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    shipping_full_name = models.CharField(max_length=255)
    shipping_email = models.CharField(max_length=255)
    shipping_address1 = models.CharField(max_length=255)
    shipping_address2 = models.CharField(max_length=255, null=True, blank=True)
    shipping_city = models.CharField(max_length=255)
    shipping_state = models.CharField(max_length=255, null=True, blank=True)
    shipping_zipcode = models.CharField(max_length=255, null=True, blank=True)
    shipping_country = models.CharField(max_length=255)

    #Don't pluralize address
    class Meta:
        verbose_name_plural = "Shipping Address"

    def __str__(self):
        return f'Shipping Address - {str(self.id)}'
    
#User -> ShippingAddress; When User is created on saved activate signal
def create_shipping_address(sender, instance, created, **kwargs):
    if created:
        #User is Created
        user_shipping = ShippingAddress.objects.create(user=instance)
        user_shipping.save()
        #print(f"++++++++ Shipping Address for User : {instance.username} has been created successfull ++++++++")
    else:
        #User updated
        #print(f"++++++++ A User {instance.username} has been updated [ ShippingAddress has been signalled ] ++++++++")
        pass

#Connecting now
post_save.connect(create_shipping_address, sender=User)

#Create Order
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    shipping_address = models.CharField(max_length=2047)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    date_ordered = models.DateTimeField(auto_now_add=True)
    shipped = models.BooleanField(default=False)
    date_shipped = models.DateTimeField(blank=True, null=True)
    #PayPal Invoice and Paid
    invoice = models.CharField(max_length=255, null=True, blank=True)
    paid = models.BooleanField(default=False)
    date_paid = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'Order -- {str(self.id)}'
    
#Now adding receiver decorator
@receiver(pre_save, sender=Order)
def set_shipped_date_on_update(sender, instance, **kwargs):
    if instance.pk:
        #This must be an update
        #in update we have pk primary key in advance
        #in creation we do not
        now = datetime.datetime.now()
        saved_obj = sender.objects.get(pk=instance.pk)
        if instance.shipped and not saved_obj.shipped:
            instance.date_shipped = now

#Create Order Item
class OrderItem(models.Model):
    order = models.ForeignKey(Order, null=True, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveBigIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'Order Item -- {str(self.id)}'

payment/forms.py
from django import forms
from .models import ShippingAddress

class ShippingForm(forms.ModelForm):
    shipping_full_name = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Full Name'}), required=True)
    shipping_email = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), required=True)
    shipping_address1 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 1'}), required=True)
    shipping_address2 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address 2'}), required=False)
    shipping_city = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City'}), required=True)
    shipping_state = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'State'}), required=False)
    shipping_zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}), required=False)
    shipping_country = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country'}), required=True)
	
    class Meta:
        model = ShippingAddress
        fields = ['shipping_full_name', 'shipping_email', 'shipping_address1', 'shipping_address2', 'shipping_city', 'shipping_state', 'shipping_zipcode', 'shipping_country']
        exclude = ['user',]

class PaymentForm(forms.Form):
    card_name = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name on Card'}), required=True)
    card_number = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Card Number'}), required=True)
    card_exp_date = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Card Expiration Date'}), required=True)
    card_cvv_number = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'CVV Number'}), required=True)
    card_address1 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Address1'}), required=True) 
    card_address2 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Address2'}), required=False)
    card_city = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing City'}), required=True)
    card_state = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing State'}), required=False)
    card_zipcode = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Zipcode'}), required=False)
    card_country = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Billing Country'}), required=True)

payment/views.py
from django.shortcuts import render, redirect
from cart.cart import Cart
#Local Imports
from .models import ShippingAddress, Order, OrderItem
from store.models import Profile
from .forms import ShippingForm, PaymentForm
from django.contrib import messages
import datetime
from authorization.authorize import Authorization
#PayPal Stuff
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm 
from django.conf import settings
import uuid # for generating unique order id
#Include Management
from .order_management import OrderManagement

#shipping status
@Authorization.authorize_server(name='update_shipping_status')
def update_shipping_status(request):
    if request.user.is_authenticated and request.user.is_superuser and request.method == 'POST':
        status = request.POST['shipping_status']
        num = int(request.POST['num']) #primary-key
        now = datetime.datetime.now()
        #For update to work, we need to use filter instead of get
        #update is used to update multiple instances
        order = Order.objects.get(id=num)
        if status == "true":
            order.shipped = True
            order.date_shipped = now
        else:
            order.shipped = False
        #Now do saving
        order.save()
        messages.success(request, ('Shipping Status Updated'))
        return redirect('store:home')
    else:
        messages.success(request, ('Access Denied'))
        return redirect('store:home')  

#orders
@Authorization.authorize_server(name='orders')
def orders(request, pk):
    if request.user.is_authenticated and request.user.is_superuser:
        #Get Order
        order = Order.objects.get(id=pk)
        #Get Corresponding items
        items = OrderItem.objects.filter(order=order)
        context = {
            'order': order,
            'items': items
        }
        return render(request, 'payment/orders.html', context)
    else:
        messages.success(request, ('Access Denied'))
        return redirect('store:home') 

#Shipped Dashboard
@Authorization.authorize_server(name='shipped_dash')
def shipped_dash(request):
    if request.user.is_authenticated and request.user.is_superuser:
        orders = Order.objects.filter(shipped=True)
        return render(request, 'payment/shipped_dash.html', {'orders' : orders}) 
    else:
        messages.success(request, ('Access Denied'))
        return redirect('store:home')

#Un-Shipped Dashboard
@Authorization.authorize_server(name='not_shipped_dash')
def not_shipped_dash(request):
    if request.user.is_authenticated and request.user.is_superuser:
        orders = Order.objects.filter(shipped=False)
        return render(request, 'payment/not_shipped_dash.html', {'orders' : orders}) 
    else:
        messages.success(request, ('Access Denied'))
        return redirect('store:home')

# Create your views here.
@Authorization.authorize_server(name='payment_success')
def payment_success(request):
    #We need to clear session and clear old-cart
    OrderManagement.clear_both_cart_session_as_well_as_db(request)
    if request.GET:
        #Trying to pull paypal stuff
        pass
    return render(request, 'payment/payment_success.html', {})

@Authorization.authorize_server(name='payment_failed')
def payment_failed(request):
    return render(request, 'payment/payment_failed.html', {})

# Checkout
@Authorization.authorize_server(name='checkout')
def checkout(request):
    #get the cart
    cart = Cart(request)
    #get products
    cart_products = cart.get_prods()
    #get quantities
    quantities = cart.get_quants();
    #get totals
    totals = cart.get_total()
    #preparing data
    context = {
        'cart_products' : cart_products,
        'quantities' : quantities,
        'totals': totals,
    }
    #Now working for form
    if request.user.is_authenticated:
        #Get user_shipping_address
        user_shipping_address = ShippingAddress.objects.get(user__id=request.user.id)
        #Get user shipping form
        shipping_form = ShippingForm(request.POST or None, instance=user_shipping_address)
        #packing in context dictionary
        context['shipping_form'] = shipping_form
        return render(request, 'payment/checkout.html', context)
    #Now the general part where no user is authenticated, we call this a guest user
    shipping_form = ShippingForm(request.POST or None)
    #packing in context dictionary
    context['shipping_form'] = shipping_form
    return render(request, 'payment/checkout.html', context)

#Billing Info
@Authorization.authorize_server(name='billing_info')
def billing_info(request):
    if request.POST:
        #Data were submitted
        #A -- get the cart
        cart = Cart(request)
        #get products
        cart_products = cart.get_prods()
        #get quantities
        quantities = cart.get_quants();
        #get totals
        totals = cart.get_total()
        #preparing data
        context = {
            'cart_products' : cart_products,
            'quantities' : quantities,
            'totals': totals,
        }
        #Let us handle shipping_info as well as billing_form
        #same whether user is authenticated or not
        #B -- shipping_info
        shipping_info = request.POST
        # Saving shipping info in session, so we can
        # take them to payment page
        request.session['my_shipping'] = shipping_info
        context['shipping_info'] = shipping_info
        #C -- billing_form , we need form forms.Form
        billing_form = PaymentForm()
        context['billing_form'] = billing_form
        #D -- Apart from normal Payment form with credit cards
        #       we also need PayPalPaymentsForm actual this is a button
        host = request.get_host() #we need host so reverse can work
        #create invoice number
        my_invoice = str(uuid.uuid4());
        #paypal dictionary
        paypal_dict = {
            'business' : settings.PAYPAL_RECEIVER_EMAIL,
            'amount' : totals,
            'item_name': 'Book Order',
            'no_shipping': '2',
            'invoice': my_invoice,
            'currency_code': 'USD', #You can do EUR etc, TZ/TZS I do not know
            'notify_url' : 'https://{}{}'.format(host, reverse('payment:paypal-ipn')),
            'return_url' : 'https://{}{}'.format(host, reverse('payment:payment_success')),
            'cancel_return' : 'https://{}{}'.format(host, reverse('payment:payment_failed')),
        }
        #Now pack paypal_form
        paypal_form = PayPalPaymentsForm(initial=paypal_dict)
        context['paypal_form'] = paypal_form
        #We need to actual create invoice with the same invoice-number
        #as PayPal , invoice is just an order marked as UNPAID
        OrderManagement.initialize_order(request, my_invoice)
        #We have our Order this is great
        return render(request, 'payment/billing_info.html', context)
    else:
       messages.success(request, ('Access Denied'))
       return redirect('store:home') 


@Authorization.authorize_server(name='process_payment')
def process_payment(request):
    if request.POST:
        #Initialize order
        OrderManagement.initialize_order(request)
        #Clearing Cart
        OrderManagement.clear_both_cart_session_as_well_as_db(request)
        #feedback
        messages.success(request, ('Order Placed Successful'))
        return redirect('store:home')
    else:
        messages.success(request, ('Access Denied'))
        return redirect('store:home')

templates/payment/billing_info.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Billing Info</h1>
            <p class="lead fw-normal text-white-50 mb-0">Enter Your Payment Info</p>
        </div>
    </div>
</header>
<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <!--Order Summary-->
            <div class="mt-5 px-5">
                <div class="card">
                    <div class="card-header">
                        Order Summary
                    </div>
                    <div class="card-body">
                        {% for product in cart_products %}
                        {{ product.name }} :
                        {% if product.is_sale %}
                        {{ product.sale_price }}
                        {% else %}
                        {{ product.price }}
                        {% endif %}
                        <br />
                        <small>Quantity:
                            {% for key, value in quantities.items %}
                            {% if key == product.id|slugify %}
                            {{ value }}
                            {% endif %}
                            {% endfor %}
                        </small>
                        <br /><br />
                        {% endfor %}
                        <strong>Total: ${{ totals }}</strong>
                        <br />
                        <a href="{% url 'cart:cart_summary' %}" class="btn btn-sm btn-outline-secondary">Update
                            Items</a>
                    </div>
                </div>
            </div>
            <!--Shipping Information-->
            <div class="mt-5 mb-5 px-5">
                <div class="card">
                    <div class="card-header">
                        Shipping Info
                    </div>
                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Value</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>Name</td>
                                    <td>{{ shipping_info.shipping_full_name }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">2</th>
                                    <td>Email</td>
                                    <td>{{ shipping_info.shipping_email }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td>Address 1</td>
                                    <td>{{ shipping_info.shipping_address1 }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">4</th>
                                    <td>Address 2</td>
                                    <td>{{ shipping_info.shipping_address2 }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">5</th>
                                    <td>City</td>
                                    <td>{{ shipping_info.shipping_city }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">6</th>
                                    <td>State</td>
                                    <td>{{ shipping_info.shipping_state }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">7</th>
                                    <td>Zipcode</td>
                                    <td>{{ shipping_info.shipping_zipcode }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">8</th>
                                    <td>Country</td>
                                    <td>{{ shipping_info.shipping_country }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <br />
                        <a href="{% url 'payment:checkout' %}" class="btn btn-outline-secondary">Update Shipping</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <!--Billing Information-->
            <div class="mt-5 mb-5 px-5">
                <div class="card">
                    <div class="card-header">
                        Billing Info
                    </div>
                    <div class="card-body">
                        <!--PayPalButton-->
                        <div class="p-1 m-1 border border-primary">
                            <center>
                                {{ paypal_form.render }}
                            </center>
                        </div>
                        <!--Normal Credit Form-->
                        <div class="p-1 m-1 border border-primary">
                            <form method="POST" action="{% url 'payment:process_payment' %}">
                                {% csrf_token %}
                                {{ billing_form.as_p }}
                                <br />
                                <button type="submit" class="btn btn-secondary">Pay Now</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    (function ($) {
        $(function () { });
    })(jQuery);
</script>
{% endblock %}

templates/payment/checkout.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Checkout</h1>
            <p class="lead fw-normal text-white-50 mb-0">Review Your Order</p>
        </div>
    </div>
</header>
<!-- Section-->
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <!--Order Summary-->
            <div class="mt-5">
                <div class="card">
                    <div class="card-header">
                        Order Summary
                    </div>
                    <div class="card-body">
                        {% for product in cart_products %}
                        {{ product.name }} :
                        {% if product.is_sale %}
                        {{ product.sale_price }}
                        {% else %}
                        {{ product.price }}
                        {% endif %}
                        <br />
                        <small>Quantity:
                            {% for key, value in quantities.items %}
                            {% if key == product.id|slugify %}
                            {{ value }}
                            {% endif %}
                            {% endfor %}
                        </small>
                        <br /><br />
                        {% endfor %}
                        <strong>Total: ${{ totals }}</strong>
                        <br />
                        <a href="{% url 'cart:cart_summary' %}" class="btn btn-sm btn-outline-secondary">Update
                            Items</a>
                    </div>
                </div>
            </div>
            <!--Shipping Information-->
            <div class="mt-5 mb-5">
                <div class="card">
                    <div class="card-header">
                        Shipping Info
                    </div>
                    <div class="card-body">
                        <form action="{% url 'payment:billing_info' %}" method="POST">
                            {% csrf_token %}
                            {{ shipping_form.as_p }}
                            <br/>
                            <button type="submit" class="btn btn-secondary">Continue To Billing</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    (function ($) {
        $(function () { });
    })(jQuery);
</script>
{% endblock %}

templates/payment/not_shipped_dash.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Un-shipped Orders</h1>
            <p class="lead fw-normal text-white-50 mb-0">Orders which are not yet shipped ...</p>
        </div>
    </div>
</header>
<!--Section-->
<section class="py-5">
    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    <!--Begin : Put Your Stuff Here-->
                    <h3>Unshipped Orders</h3>
                    {% if orders %}
                    <table class="table table-striped table-hover table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th scope="col">Order</th>
                                <th scope="col">Price</th>
                                <th scope="col">Customer Email</th>
                                <th scope="col">Date Ordered</th>
                                <th scope="col">Shipped</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in orders %}
                                <tr>
                                    <th scope="row"><a href="{% url 'payment:orders' item.id %}">{{ item.id }}</a></th>
                                    <td>{{ item.amount_paid }}</td>
                                    <td>{{ item.email }}</td>
                                    <td>{{ item.date_ordered }}</td>
                                    <td>
                                        <form action="{% url 'payment:update_shipping_status' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="shipping_status" value="true"/>
                                            <input type="hidden" name="num" value="{{ item.id }}"/>
                                            <button type="submit" class="btn btn-success btn-sm">Mark Shipped</button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="alert alert-warning" role="alert">
                        Your list is Empty
                    </div>
                    {% endif %}
                    <!--End : Put Your Stuff Here-->
                </div>
            </center>
        </div>
    </div>
</section>
<!-- Section-->
{% endblock %}

templates/payment/payment_failed.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Payment Failed ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">There was a problem ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            There was a problem in processing your order. Please Try Again .....
        </div>
    </div>
</section>
    {% endblock %}

templates/payment/payment_success.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Payment Success ...</h1>
            <p class="lead fw-normal text-white-50 mb-0">Your Order is complete ...</p>
        </div>
    </div>
</header>
<!--Section-->
<!-- Section-->
<section class="py-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            Your Order has been Completed Successful
        </div>
    </div>
</section>
    {% endblock %}

templates/payment/shipped_dash.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shipped Orders</h1>
            <p class="lead fw-normal text-white-50 mb-0">Orders which has been shipped ...</p>
        </div>
    </div>
</header>
<!--Section-->
<section class="py-5">
    <div class="container">
        <div class="row">
            <center>
                <div class="col-8">
                    <!--Begin : Put Your Stuff Here-->
                    <h3>Shipped Orders</h3>
                    {% if orders %}
                    <table class="table table-striped table-hover table-bordered">
                        <thead class="table-dark">
                            <tr>
                                <th scope="col">Order</th>
                                <th scope="col">Price</th>
                                <th scope="col">Customer Email</th>
                                <th scope="col">Date Shipped</th>
                                <th scope="col">Shipped</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in orders %}
                            <tr>
                                <th scope="row"><a href="{% url 'payment:orders' item.id %}">{{ item.id }}</a></th>
                                <td>{{ item.amount_paid }}</td>
                                <td>{{ item.email }}</td>
                                <td>{{ item.date_shipped }}</td>
                                <td>
                                    <form action="{% url 'payment:update_shipping_status' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="shipping_status" value="false"/>
                                        <input type="hidden" name="num" value="{{ item.id }}"/>
                                        <button type="submit" class="btn btn-danger btn-sm">Mark Unshipped</button>
                                    </form>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <div class="alert alert-warning" role="alert">
                        Your list is Empty
                    </div>
                    {% endif %}
                    <!--End : Put Your Stuff Here-->
                </div>
            </center>
        </div>
    </div>
</section>
<!-- Section-->
{% endblock %}